export const experienceContent = [
  {
    company: 'American Express',
    role: 'Software Engineer III',
    dateRange: 'August 2021 - Now',
    description: 'Working within the LoungeBuddy organization within the American Express company to take our startup up and off the ground. I am deeply involved in every aspect of the development process, working as a full-stack developer.',
    subtitle: 'Primary Responsibilities',
    bullets: [
      'Leveraged latest best practices for both front-end and backend facing technologies through the development of an updated promo code tool',
      'Streamlined the customer support process by creating a system to create, schedule, and manage promo codes as well as support tracking of their metrics',
      'Developed a a set of reusable components based on the LoungeBuddy design system for reuse across all LoungeBuddy web properties, accelerating time-to-market period for supported features in the future',
      'Ramped up on the LoungeBuddy interview process by learning to conduct both front-end and backend-oriented engineering interviews',
    ],
    stack: [
      'React.js',
      'Next.js',
      'Chakra UI',
      'Node.js',
      'React-Query',
      'Recoil.js',
      'Abstract',
    ],
    imagePath: './experience/amex.png',
  },
  {
    company: 'T-Mobile',
    role: 'Product & Technology Intern',
    dateRange: 'May 2021 - August 2021',
    description: 'Worked with the Digital Team at T-Mobile to streamline internal processes in a fully remote internship.',
    subtitle: 'Internship Experience',
    bullets: [
      'Provided direction and guidance for process improvement and account for governance policies that represent the department to various customers and stakeholders',
      'Consulted with cross-functional teams to detail insights that drive strategic initiatives and projects that outline corporate prioritization with actionable plans',
      'Documented business operations requirements, utilizing best practices and communicating updates and tracking progress of efforts',
      'Ensured business continuity efforts are maintained and evolve as capabilities improve and become more robust',
    ],
    imagePath: './experience/tmobile.svg',
  },
  {
    company: 'Nelnet',
    role: 'Software Engineer Intern',
    dateRange: 'June 2020 - May 2021',
    description:
      'Participated in a fully remote internship in a primary role as a Front-End Developer on Nelnet\'s Campus Key team.',
    subtitle: 'Things I\'ve Done',
    bullets: [
      'Redeveloped the front-end for the Cardholder Portal application using React.js',
      'Leveraged Material-UI for faster and easier web development',
      'Developed dynamically scalable iOS applications with Swift, UIKit, and the serverless framework',
      'Designed and developed rich, interactive user experiences utilizing the power of UIKit',
    ],
    stack: [
      'React.js',
      'Material-UI',
      'Amazon Web Services',
      'Material-Table',
      'Swift',
      'UIKit',
      'Figma',
    ],
    imagePath: './experience/nelnet.svg',
  },
  {
    company: 'Hoffman Strategy Group',
    role: 'Software Engineer & Product Manager',
    dateRange: 'November 2019 - September 2020',
    description:
      'Inherited the pre-existing Hoffman Analytics senior design project from a team of students at the University of Nebraska-Lincoln and worked to lead the redevelopment of an online commercial real estate feasibility analytics and client report generation system.',
    subtitle: 'System Capabilities',
    bullets: [
      'Quickly organize data by project to upload and download files with ease',
      'Directly integrate with a variety of Amazon Web Services to store files, authenticate users, and create and store project information',
      'Search, filter, and compare projects to painlessly track down similar markets',
      'Easily upload and download files to a variety of projects with bulk capabilities',
    ],
    stack: [
      'React.js',
      'Material-UI',
      'Create React App',
      'Redux',
      'Amazon Web Services',
      'React-Router',
      'GraphQL',
      'Material-Table',
      'Python',
      'Selenium',
    ],
    imagePath: './experience/hsg.png',
  },
  {
    company: 'Raven Industries',
    role: 'Software Engineer Intern',
    dateRange: 'May 2019 - August 2019',
    description:
      'Developed and maintained a report generation tool that streamlined internal processes and consolidated large batches of data into one place.',
    subtitle: 'System Capabilities',
    bullets: [
      'Easily export database information onto a formatted PDF',
      'Filter through 2,000 database entries quickly and easily based on their defined relationships between one another',
      'Query a unit\'s corresponding data at the touch of a button to be displayed in a sensical, easy-to-understand user interface',
    ],
    stack: ['JavaScript', 'Kendo UI', 'jQuery', 'ASP.NET Core', 'MySQL', 'CSS'],
    imagePath: './experience/raven.png',
  },
  {
    company: 'University of Nebraska-Lincoln',
    role: 'Teaching Assistant',
    dateRange: 'January 2019 - May 2020',
    description:
      'Aided Dr. Bohn in the planning and execution of his CSCE 361 (Software Engineering) course while also grading student assignments and holding weekly office hours.',
    subtitle: 'Responsibilities',
    bullets: [
      'Managed three student software teams as they tackled a semester-long development project',
      'Authored concise tutorials for the use of the JavaFX Scene Builder in conjunction with IntelliJ IDEA',
      'Drove several changes to the contents of the midterm exam(s) after peer-review',
    ],
    stack: ['Java', 'JavaFX', 'GitLab'],
    imagePath: './experience/unlcoe.png',
  },
  {
    company: 'Re-Logic Games',
    role: 'Quality Assurance Game Tester',
    dateRange: 'January 2011 - June 2015',
    description:
      'Evaluated beta versions of the hit indie game Terraria for bugs and gameplay issues prior to shipping out major community updates.',
    subtitle: 'Fun Facts',
    bullets: [
      'As of April 2020, Terraria has sold 30 million copies worldwide',
      'At the time of my recruitment, I was only 12 years old, making me the youngest quality assurance tester on the team by a mile',
      'Terraria was never projected to become as large as it did',
      'My experience with Re-Logic games was what fueled my initial interest in software development',
    ],
    stack: ['Jira', 'Slack', 'XChat', 'Dropbox'],
    imagePath: './experience/re-logic.png',
  },
];
