export const experienceContent = [
  {
    company: "Nelnet",
    role: "Software Engineer Intern",
    dateRange: "June 2020 - Present",
    description: "Currently participating in a fully remote internship where I have rotated between two teams and three projects since starting work in June. In my current role, I am working as a Software Engineer Intern on Nelnet's Campus Key team, redeveloping the front-end for the Cardholder Portal web application, an internal administrative portal for our Campus Key mobile application. Some of my duties within the company have and currently include:",
    bullets: ["Redevelop the front-end for the Cardholder Portal application using the React.js framework", "Leverage Material-UI for faster and easier web development", "Develop dynamically scalable iOS applications with Swift, UIKit, and the serverless framework", "Design and develop rich, interactive user experiences utilizing the power of UIKit"],
    tech: ["React.js", "Material-UI", "Amazon Web Services", "Figma", "Swift", "UIKit"],
    imagePath: "./experience/nelnet.svg",
  },
  {
    company: "Hoffman Strategy Group",
    role: "Software Engineer & Product Manager",
    dateRange: "November 2019 - September 2020",
    description: "My partner and I, Matt Sichterman, inherited a pre-existing JavaScript codebase and worked together to redefine the product vision for the Hoffman Analytics platform. We lead the redevelopment of an online commercial real estate feasibility analytics and client report generation system. This enhanced system allows you to:",
    bullets: ["Quickly organize data by project to upload and download files with ease", "Directly integrate with a variety of Amazon Web Services to store files, authenticate users, and create and store project information", "Search, filter, and compare projects to painlessly track down similar markets", "Easily upload and download files to a variety of projects with bulk capabilities"],
    tech: ["React.js", "Material-UI", "Amazon Web Services", "Redux", "GraphQL"],
    imagePath: "./experience/hsg.png"
  },
  {
    company: "Raven Industries",
    role: "Software Engineer Intern",
    dateRange: "May 2019 - August 2019",
    description: "Developed and maintained an internal report generation tool that streamlined the process of creating large, easy-to-read component reports. The system was built entirely new when I joined Raven using out-of-the-box web development toolsets like .NET Core and Kendo UI. This system allowed a user to:",
    bullets: ["Easily export database information onto a formatted PDF", "Filter through 2,000 database entries quickly and easily based on their defined relationships between one another", "Query a unit's corresponding data at the touch of a button to be displayed in a sensical, easy-to-understand user interface"],
    tech: ["JavaScript", "Kendo UI", "jQuery", "ASP.NET Core", "MySQL"],
    imagePath: "./experience/raven.png",
  },
  {
    company: "University of Nebraska-Lincoln",
    role: "Teaching Assistant",
    dateRange: "January 2019 - May 2020",
    description: "Aided Dr. Bohn in the planning and execution of his CSCE 361 (Software Engineering) course while also grading student assignments and holding weekly office hours. In this position, I also:",
    bullets: ["Managed three student software teams as they tackled a semester-long development project", "Authored concise tutorials for the use of the JavaFX Scene Builder in conjunction with IntelliJ IDEA", "Drove several changes to the contents of the midterm exam(s) after peer-review"],
    tech: ["Java", "JavaFX", "GitLab",],
    imagePath: "./experience/unl.png",
  },
  {
    company: "Re-Logic Games",
    role: "Quality Assurance Game Tester",
    dateRange: "January 2011 - June 2015",
    description: "Evaluated beta versions of the hit indie game Terraria for bugs and gameplay issues prior to shipping out major community updates. Fun facts",
    bullets: ["Terraria has sold 30 MILLION copies worldwide", "Being that I joined the team in early 2011, I was only 12 years old at the time", "We never expected Terraria to get as big as it did"],
    tech: ["Jira", "Slack", "XChat", "Dropbox",],
    imagePath: "./experience/re-logic.png",
  },
];